# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField()),
                ('text', models.TextField()),
                ('delay', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo_app.Board'),
        ),
    ]
